export const GET_COLLECTIONS = 'GET_COLLECTIONS'
export const GET_CURRENT_COLLECTION = 'GET_CURRENT_COLLECTION'
export const LOAD_MORE_PHOTOS = 'LOAD_MORE_PHOTOS'
export const CLEAR_CURRENT_COLLECTION = 'CLEAR_CURRENT_COLLECTION'
